### ISSUE TITLE
TCP write crashes

### ISSUE THREAD

**Issue by hkoosha** [hkoosha/homer2#4]
```gdb
(gdb) bt
#0  isr_svcall () at /opt/piko/pico/pico-sdk/src/rp2_common/pico_standard_link/crt0.S:99
#1  <signal handler called>
#2  0x10014444 in tcp_output (pcb=pcb@entry=0x2000f1a0 <memp_memory_TCP_PCB_base+656>) at /opt/piko/pico/pico-sdk/lib/lwip/src/core/tcp_out.c:1393
#3  0x100108a6 in tcp_close_shutdown_fin (pcb=pcb@entry=0x2000f1a0 <memp_memory_TCP_PCB_base+656>) at /opt/piko/pico/pico-sdk/lib/lwip/src/core/tcp.c:448
#4  0x100111ee in tcp_close_shutdown (pcb=0x2000f1a0 <memp_memory_TCP_PCB_base+656>, rst_on_unacked_data=rst_on_unacked_data@entry=1 '\001') at /opt/piko/pico/pico-sdk/lib/lwip/src/core/tcp.c:403
#5  0x1001122a in tcp_close (pcb=<optimized out>) at /opt/piko/pico/pico-sdk/lib/lwip/src/core/tcp.c:498
#6  0x10000558 in homer2::Homer2Pusher::close (this=this@entry=0x200111d8) at /home/username/git/homer2/board/src/homer2_pusher.cpp:601
#7  0x100015aa in homer2::Homer2Pusher::write (this=this@entry=0x200111d8) at /home/username/git/homer2/board/src/homer2_pusher.cpp:583
#8  0x100018da in homer2::Homer2Pusher::tryPush (this=this@entry=0x200111d8) at /home/username/git/homer2/board/src/homer2_pusher.cpp:291
#9  0x10002900 in homer2::Homer2Pusher::push (this=0x200111d8, data=...) at /home/username/git/homer2/board/src/homer2_pusher.cpp:170
#10 0x1000b672 in (anonymous namespace)::ring0 (sensors=..., pusher=...) at /home/username/git/homer2/board/src/homer2_main.cpp:179
#11 0x1000bacc in (anonymous namespace)::ring1 () at /home/username/git/homer2/board/src/homer2_main.cpp:217
#12 0x1000bb94 in (anonymous namespace)::ring2 () at /home/username/git/homer2/board/src/homer2_main.cpp:225
#13 0x1000bdf6 in homer2_main () at /home/username/git/homer2/board/src/homer2_main.cpp:244
#14 0x100002e2 in main () at /home/username/git/homer2/board/homer2.c:9
```

**Comment by hkoosha** [comment]
Probably fixed in https://github.com/hkoosha/homer2/commit/99e24ba570c9c6d120f423a927846c2657d3f485
